export const INDUSTRIES = [
  'construction',
  'architecture',
  'real_estate',
  'interior_design',
  'legal',
  'finance',
  'accounting',
  'consulting',
  'professional_services',
  'medical',
  'dental',
  'wellness',
  'fitness',
  'beauty',
  'spa',
  'restaurant',
  'cafe',
  'hospitality',
  'catering',
  'retail',
  'fashion',
  'ecommerce',
  'technology',
  'saas',
  'enterprise_software',
  'fintech',
  'startup',
  'education',
  'photography',
  'events',
  'creative_services',
  'nonprofit',
  'automotive',
  'logistics',
] as const

export const DESIGN_STYLES = [
  'bold-modern',
  'minimal-luxury',
  'warm-professional',
  'technical-authority',
  'editorial',
  'playful',
  'corporate-safe',
  'dark-premium',
  'organic-natural',
] as const

export const AUDIENCES = [
  'enterprise',
  'b2b-professional',
  'smb',
  'local-consumer',
  'high-net-worth',
  'direct-consumer',
  'young-professional',
  'homeowner',
  'parent',
] as const

export const USE_CASE_TAGS = [
  'lead-gen',
  'trust-first',
  'portfolio-showcase',
  'local-seo',
  'product-demo',
  'service-explainer',
  'premium-positioning',
  'appointment-booking',
  'high-volume',
  'awareness',
  'multi-product',
] as const

export const SECTION_TAGS = [
  'bold-opener',
  'minimal-opener',
  'trust-anchor',
  'social-proof',
  'logo-wall',
  'proof-gallery',
  'service-grid',
  'feature-highlight',
  'process-explainer',
  'stats-proof',
  'testimonial',
  'team-showcase',
  'local-signal',
  'media-heavy',
  'visual-break',
  'conversion-close',
  'dark-treatment',
  'dual-cta',
  'product-showcase',
  'pricing-display',
  'persona-segmentation',
  'b2b-credibility',
  'case-studies',
  'mobile-app',
  'enterprise-nav',
  'resource-hub',
  'footer',
  'brand-statement',
  'human-context',
  'buyer-segmentation',
  'versatility-proof',
] as const

export const SECTION_TYPES = [
  'hero',
  'trust_bar',
  'services',
  'portfolio',
  'testimonials',
  'stats',
  'team',
  'process',
  'pricing',
  'faq',
  'cta',
  'footer',
  'about',
  'contact',
  'gallery',
] as const
